name: projeto_mobile
description: A new Flutter project.

# Remova a linha abaixo se você pretende publicar o projeto no pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1  # Certifique-se de manter o mesmo pacote de lints definido no analysis_options.yaml

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-logo.png  # A indentação está correta aqui, garantindo que o Flutter encontre os ativos.
